### ISSUE TITLE
Unable to reproduce published results

### ISSUE THREAD

**Issue by Tobi2K** [shizhediao/R-Tuning#10]
Hi all,
First, thank you a lot for your work! I think it is very interesting. Congratulations on the Outstanding Paper Award at NAACL 2024!
I am currently trying to reproduce your results following the steps in the README. I installed LMFlow as described.
For any potential insight, all the commands I ran are the following:
Training:
```
cd training
cd pararel
python run_pararel.py --model huggyllama/llama-7b --method unsure
```

Finetuning:
```
cd ../../LMFlow/
./scripts/run_finetune.sh --model_name_or_path huggyllama/llama-7b --dataset_path ../training/training_data/ --output_model_path output_models/finetuned_huggy_llama_7b
```

Evaluation:
```
cd ../evaluation/pararel/
python evaluate.py --model ../../LMFlow/output_models/finetuned_huggy_llama_7b/ --domain ID --result ParaRel_huggyllama_7b
cd results/
python calculate_ap.py --result ParaRel_huggyllama_7b_ID.json
```

These steps result in an AP Score of about 0.17.
I tried to find any steps described in the paper I may be missing, but I could not find any. Do you see anything missing? I would greatly appreciate any help!

Best Regards,
Tobi

**Comment by hanningzhang** [comment]
Hi. Thank you so much for your interest in the R-Tuning paper.
I think the problem occurs during the fine-tuning process.

For the script `./scripts/run_finetune.sh`, the default training epoch is 0.01 so the model might not be well trained.
You might need to change the epoch to 1.

We are sorry for the missing information.

**Comment by Tobi2K** [comment]
Hi, that's great! This fixed the issue! 

Thanks for your help!
