### ISSUE TITLE
Measurement between Ground-truth Answer and Model's Answer may be too Naive?

### ISSUE THREAD

**Issue by Cloud-Iris** [shizhediao/R-Tuning#11]
As title, in `R-Tuning/training/pararel/run_pararel.py`, I worry that **such a simple measurement method cannot produce high-quality data**.

![image](https://github.com/user-attachments/assets/591457b6-7d8b-439c-81ad-1363ab1bc34f)

In fact, I find that the 4-th question `In what field does Anaxagoras work?`, the ground truth Answer is `philosophy`, and the model's (here I use `openlm-research/open_llama_3b`) answer is `Anaxagoras was a Greek philosopher who lived in the...`. 

**Here we meet the problem**. By using the Measurement in current code, we will get `False` lead to adding `"I am unsure"` in data construction. I don't think it is good for the subsequent training and fine-tuning process. **It seems a mistake that cannot be ignored.**

By the way, I want to give a try on letting `openlm-research/open_llama_3b` to evaluate whether **Ground-truth Answer** and **Model's Answer** express the same meaning, but I got so bad results that I doubt the language ability of this model. My key code is below:

```python
full_input=f"""[Q&A]: {sample[0]} {sample[1]}.
[Statement]: {output}.
Please determine whether [Q&A] and [Statement] express the same meaning, answer me with YES or NO:"""
isSameInputs = tokenizer(full_input, return_tensors="pt").to(0)
ids = isSameInputs['input_ids']
length = len(ids[0])
isSame = model.generate(
    input_ids=ids,
    max_new_tokens = 100,
)
print("-------------------------------------")
output_text = tokenizer.decode(isSame[0][length:])
print(output_text)
print("-------------------------------------")
```

And I got some terrible results.
For prompt1:

![image](https://github.com/user-attachments/assets/84b32dbd-b392-4a55-ac18-f5fdf4039494)

I got output below:

![image](https://github.com/user-attachments/assets/f3dbd7fa-20b9-413d-92a3-d588138d0161)

For prompt2:

![image](https://github.com/user-attachments/assets/8552a307-248c-4772-80bb-708b8c77bc31)

I got output below:

![image](https://github.com/user-attachments/assets/45133aca-5dd7-4ca7-bb3b-3defc991919e)

I appreciate your work, but I am so confused about **the data construction process** and the understanding ability for model used in your work.

**Comment by shizhediao** [comment]
We proposed a way to measure the model's knowledge boundary and this is a way for implementation with good performance.
Of course, in your experiments, you could replace the model with some latest stronger model like Llama-3.2. 
Thanks!

**Comment by Cloud-Iris** [comment]
Thank you for your reply! Perhaps it is ok to explain the rationality of the **strict evaluation paradigm** by **Answer Fidelity of the Model**. I was just confused trying to reproduce it, and I didn't mean any offense.

Anyway, thank you for your work and reply~
