### ISSUE TITLE
About Dataset "NEC"

### ISSUE THREAD

**Issue by cytan17726** [shizhediao/R-Tuning#2]
Hi there!

Thank you for your excellent work！

I am interested in the open-domain dataset NEC, but I am troubled by unable to find relevant information.

Can you help me, such as providing relevant papers or dataset links? Thanks a lot!

**Comment by shizhediao** [comment]
Hi,
Thanks for your attention to our work!
For the NEC please take a look at this paper: https://arxiv.org/pdf/2311.09731.pdf
Please don't hesitate to ask if you have any further questions!

**Comment by cytan17726** [comment]
❤
